### ISSUE TITLE
Listeners are not working when i reopen the app after killing it from memory. Only force stop from app's setting will invoke the listeners again. 

### ISSUE THREAD

**Issue by suhailzoft** [QuickBlox/quickblox-flutter-sdk#38]
_callSubscription =
          await QB.webrtc.subscribeRTCEvent(QBRTCEventTypes.CALL, (data) {
}
This listener event not triggering while a call is initiated. It works on the initial app launching time. But, if we kill the app and reopen makes this issue.

**Comment by ghost** [comment]
Hello, @suhailzoft 

This is Nikolay from QuickBlox support.

Please make sure that you followed our documentation:
[https://docs.quickblox.com/docs/flutter-video-calling#manage-calls](https://docs.quickblox.com/docs/flutter-video-calling#manage-calls)

In order to investigate the issue further, please provide us with:
1. Full logs.
2. Step-by-step instructions on how to reproduce the issue.
3. Version of QuickBlox Flutter SDK.
4. Platform where the issue is reproduced (Android, iOS or both).
5. Version of the platform (e.g. Android 11, iOS 13).
6. Devices in use (e.g. Redmi 8).
7. Flutter version.
8. Dart version.

**Comment by suhailzoft** [comment]
@QB-nikolay-zolotarov 
This issue only happening on android. iOS is working fine even if i kill the app.

**Platform**
Android

**Flutter and dart version**
Flutter (Channel unknown, 2.2.3, on macOS 11.3.1 20E241 darwin-x64, locale en-IN)
Dart - 2.13.4

**Device** - realme XT, Android 11

**Quickblox SDK version** - ^0.6.1-beta

Steps to reproduce:

- Open the app
- Kill the app from the minimised apps.
- Try to trigger a call from the backend.

**Logs**
E/libEGL  (14169): Invalid file path for libcolorx-loader.so
E/libEGL  (14169): Invalid file path for libcolorx-loader.so
E/libEGL  (14169): Invalid file path for libcolorx-loader.so
W/FlutterEngineCxnRegstry(14169): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@9c062e3) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@39d74e0).
D/RNCK:VoiceConnectionService(14169): setAvailable: false
D/RNCK:VoiceConnectionService(14169): setAvailable: true
I/flutter (14169): 📷Quickblox: Trying to login
D/QBASDK  (14169): Restored custom endpoints. ApiEndpoint: , ChatEndpoint: . lastUpdateTime: Thu Jan 01 05:30:00 GMT+05:30 1970
D/QBASDK  (14169): creating app secured preferences
D/QBASDK  (14169): QBSessionListener onSessionRestored WITH USER
D/QBASDK  (14169): SubscribeService: subscribeToPushesAutomatic
D/QBASDK  (14169): =========================================================
D/QBASDK  (14169): REQUEST
D/QBASDK  (14169): HEADERS
D/QBASDK  (14169):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  (14169):     QB-SDK=Android 3.9.11
D/QBASDK  (14169): PARAMETERS
D/QBASDK  (14169): INLINE
I/DpmTcmClient(14169): RegisterTcmMonitor from: $Proxy1
D/QBASDK  (14169): SubscribeService: SubscribeService created
D/QBASDK  (14169): SubscribeService: onHandleIntent start: register to pushes
D/QBASDK  (14169): SubscribeService: Your meta-data are not set, auto push subscribe unable
D/QBASDK  (14169): SubscribeService: Service onDestroy

**Comment by ghost** [comment]
@suhailzoft
Thank you for the detailed information.

According to my check, another customer reported a similar issue with WebRTC events and it was fixed in the version 0.6.2-beta.
Here is a link:
[https://pub.dev/packages/quickblox_sdk](https://pub.dev/packages/quickblox_sdk)

Please update the QuickBlox Flutter SDK and let me know if the issue is resolved after the update.

**Comment by suhailzoft** [comment]
@QB-nikolay-zolotarov Still not working. I upgraded the library to the latest quickblox_sdk 0.6.2-beta.

**Comment by ghost** [comment]
@suhailzoft Thank you for your reply.

Please try updating Flutter to 2.5. 

Also, please let me know if other preconditions like the device and OS version are the same.

Additionally, please provide me with fresh logs after the update of the QuickBlox Flutter SDK.

**Comment by suhailzoft** [comment]
@QB-nikolay-zolotarov Not working even after i upgraded to latest flutter version 2.5.3.
I'm using realme XT (android 11).
Besides that,  the same code works in the iOS in this same condition. So, It would be the issue of SDK.

**Comment by ghost** [comment]
@suhailzoft Thank you for updating me.

Please provide logs for the application with the updated SDK.

Also, please describe in more detail in what cases the issue occurs.

**Comment by ghost** [comment]
@suhailzoft 
Please double-check the application workflow:

open app (from background or icon)
settings → init credentials
auth → login
chat → connect, subscribe to events
webrtc → init, subscribe to events
receive the call (or another) event
app goes to background
webrtc → unsubscribe, release
chat → unsubscribe, disconnect

If you follow this order, the call (and another) event should be received correctly.

**Comment by KAUSHIKTECHIE** [comment]
Hey,I have done the same flow.But Still I am facing the issue.I have sent the logs from logcat.
Chat Subsriciption not working when click on Push notification when app is in terminated/force closed state.

Note: It happens for Android and when in Terminated/Forced closed state and while click on notification.
<img width="1375" alt="Screenshot 2021-12-03 at 12 47 42 AM" src="https://user-images.githubusercontent.com/46910910/144546363-a78b8a7d-3a8a-4486-9913-a0b8b65e5ffe.png">

**Comment by ghost** [comment]
@KAUSHIKTECHIE Hello,

Please try updating the SDK to the latest version:
[https://pub.dev/packages/quickblox_sdk/versions/0.6.3-beta](https://pub.dev/packages/quickblox_sdk/versions/0.6.3-beta)

If the issue persists, please provide the following information:
1. The current version of QuickBlox Flutter SDK.
2. Platform where the issue is reproduced (Android, iOS, or both).
3. Version of the platform (e.g. Android 11, iOS 13).
4. Devices in use (e.g. Redmi 8).
5. Flutter version.
6. Dart version.
7. Is this issue intermittent or permanent?
8. What are the steps to reproduce on our side?

**Comment by KAUSHIKTECHIE** [comment]
@QB-nikolay-zolotarov Hello,
    1.Quickblox SDK - 0.6.3-beta
    2. Both
    3. Android 10 and above iOS 13 and above
    4. Oneplus , Samsung 
    5. Flutter version - 2.5.3
    6.  Dart version - 2.14.4
    7. permanent
    8. When You get notification from terminated mode of app  then clicking on it and try to send message but message delivered, message read subscription not working.Also cant received message from the subscription.
  It has always same problem.Not known why is it because subscription I have done and initialized.
Can you make this fix.Being a blocker for the app.

**Comment by SagarArora312** [comment]
Hi, Quickblox Team , I am also facing the same issue 
@QB-nikolay-zolotarov 
1.Quickblox SDK - 0.6.5-beta
2. Android 
3. Android 11(All android version is not working)
4. Realme , Samsung
5. Flutter version - 2.8.0
6. Dart version - 2.15
7. permanent
8. When You get notification from terminated mode of app then clicking on it and try to send message but message delivered, message read subscription not working.Also cant received message from the subscription.
It has always same problem.Not known why is it because subscription I have done and initialized.
Can you make this fix.Being a blocker for the app.

@KAUSHIKTECHIE Did you find any solution?

**Comment by ghost** [comment]
@KAUSHIKTECHIE @SagarArora312 
Hello,
We have created an internal ticket and forwarded it to our developers.
Once there is any news or they need more information, we will let you know.

**Comment by ghost** [comment]
@KAUSHIKTECHIE @SagarArora312 Please update the SDK to the latest version:
https://pub.dev/packages/quickblox_sdk/versions/0.6.7-beta
Here is a fix.
