### ISSUE TITLE
Error Required session does not exist on QB.auth.login

### ISSUE THREAD

**Issue by yoseptara** [QuickBlox/quickblox-flutter-sdk#62]
Why do I often get this error when using QB.auth.login after using the app for a few hours? But after clearing all data of the app (cache + data), the error doesn't occur. This means users have to clear the app data every time they get this error.

I call initSession() which has QB.auth.login inside its function in the initState() function in 1 of my page that opens after clicking a button and get this error.

QB.auth.login response body :
'{"errors":{"base":["Required session does not exist"]}}'

Error image :
![Screen Shot 2023-02-12 at 17 21 59](https://user-images.githubusercontent.com/49258329/218302812-a4470745-1dc0-427d-acd3-8f02e2ad97a3.png)

quickblox_service.dart code :
```
Future<QuickbloxService> init() async {
    await QB.settings.init(APP_ID, AUTH_KEY, AUTH_SECRET, ACCOUNT_KEY);
    await Future.wait(
      [
        enableAutoReconnect(),
        initStreamManagement(),
      ],
    );
    return this;
  }

  Future<void> initSession(
    String email,
  ) async {
    await loginOrRegister(email);
  }
  
    Future<void> loginOrRegister(String email) async {
    try {
      await login(email);
    } catch (exception) {
      if(exception.toString().contains('Client is already logged in')) {
        return;
      } else if (exception is PlatformException) {

        if (exception.code == 'Unauthorized') {
          await registerQB(email, email);
          await login(email);
          return;
        }
      }

      throw '(qbService.loginQB) error : ${exception.toString()}';
    }
  }

  Future<void> login(String email) async {
    QBLoginResult result = await QB.auth.login(
      email,
      email,
    );
    setUser = result.qbUser;
    setSession = result.qbSession!;
  }
  
   Future<void> registerQB(String email, String password) async {
    try {
      await QB.users.createUser(email, password, email: email);
    } catch (exception) {
      throw '(QuickbloxService.registerQB) error : ${exception.toString()}';
    }
  }
  
    Future<void> enableAutoReconnect() async {
    try {
      await QB.settings.enableAutoReconnect(true);
    } catch (exception, stackTrace) {
      // Some error occurred, look at the exception message for more details
      Funcs.logError(exception, stackTrace);
    }
  }

  Future<void> enableCarbons() async {
    await QB.settings.enableCarbons();

  }

  Future<void> initStreamManagement() async {
    bool autoReconnect = true;
    int messageTimeout = 5;
    try {
      await QB.settings.initStreamManagement(messageTimeout, autoReconnect: autoReconnect);
    } catch (exception) {
      throw '(qbService.initStreamManagement) error : ${exception.toString()}';
    }
  }
  ```
  
  main.dart code :
  ```
  void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Future.wait(
    [
      Firebase.initializeApp(),
      initServices(),
      GetStorage.init(),
      // PackageInfo.fromPlatform(),
    ],
  );

  // final NotificationService _notificationService = NotificationService();
  final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();
  await _flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(kAndroidNotifChannel);
  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );
  await NotificationService.requestPermission();
  NotificationService.configLocalNotification();

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;

  Isolate.current.addErrorListener(RawReceivePort((pair) async {
    final List<dynamic> errorAndStacktrace = pair;
    await FirebaseCrashlytics.instance.recordError(
      errorAndStacktrace.first,
      errorAndStacktrace.last,
    );
  }).sendPort);
  runZonedGuarded<Future<void>>(
    () async {
      HttpOverrides.global = new MyHttpOverrides();
      runApp(
        MyApp(),
      );
    },
    (exception, stackTrace) async {
      debugPrint(exception.toString());
      debugPrintStack(stackTrace: stackTrace);
      FirebaseCrashlytics.instance.recordError(exception, stackTrace);
    },
  );
}

Future<void> initServices() async {
  await Future.wait(
    [
      Get.putAsync(() => QuickbloxService().init()),
    ],
  );
}
```

Flutter doctor :
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale en-ID)
    • Flutter version 3.3.10 on channel stable at /Users/Tara/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/Tara/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by kirillTolmachev** [comment]
Hello @yoseptara 
Maybe your problem relates to "after a few hours" of inactivity application (background for example).

To investigate the problem and find a solution, please provide more details:
1. Version of Quickblox Flutter SDK which you use in the project
2. Logs with Request/Response (now we have only one response) for all steps when your application starts after a few hours.

**Comment by yoseptara** [comment]
> Hello @yoseptara Maybe your problem relates to "after a few hours" of inactivity application (background for example).
> 
> To investigate the problem and find a solution, please provide more details:
> 
> 1. Version of Quickblox Flutter SDK which you use in the project
> 2. Logs with Request/Response (now we have only one response) for all steps when your application starts after a few hours.

1. quickblox_sdk: ^0.11.0

2. Request/Response (before error occurs) :
```
D/QBASDK  ( 9477): =========================================================
D/QBASDK  ( 9477): === REQUEST ==== d7b30726-8e06-4f78-8b40-642513e16479 ===
D/QBASDK  ( 9477): REQUEST
D/QBASDK  ( 9477):     GET https://api.quickblox.com/account_settings.json
D/QBASDK  ( 9477): HEADERS
D/QBASDK  ( 9477):     QB-Account-Key=**HIDDEN**
D/QBASDK  ( 9477): PARAMETERS
D/QBASDK  ( 9477): 
D/QBASDK  ( 9477): INLINE
D/QBASDK  ( 9477):     GET https://api.quickblox.com/account_settings.json
D/TrafficStats( 9477): tagSocket(173) with statsTag=0xffffffff, statsUid=-1
D/InsetsController( 9477): show(ime(), fromIme=true)
D/EGL_emulation( 9477): app_time_stats: avg=2089.86ms min=0.90ms max=41572.08ms count=20
D/EGL_emulation( 9477): app_time_stats: avg=25.73ms min=1.41ms max=90.70ms count=32
D/QBASDK  ( 9477): *********************************************************
D/QBASDK  ( 9477): *** RESPONSE *** d7b30726-8e06-4f78-8b40-642513e16479 ***
D/QBASDK  ( 9477): STATUS : 200 
D/QBASDK  ( 9477): HEADERS
D/QBASDK  ( 9477):     Access-Control-Allow-Origin=*
D/QBASDK  ( 9477):     Cache-Control=max-age=0, private, must-revalidate
D/QBASDK  ( 9477):     Connection=close
D/QBASDK  ( 9477):     Content-Length=124
D/QBASDK  ( 9477):     Content-Security-Policy=default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data: www.google-analytics.com; object-src 'none'; script-src 'self' https: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com; style-src 'self' https: 'unsafe-inline'
D/QBASDK  ( 9477):     Content-Type=application/json; charset=utf-8
D/QBASDK  ( 9477):     Date=Fri, 17 Feb 2023 04:45:19 GMT
D/QBASDK  ( 9477):     ETag=W/"e545561202e48f08ebd0483cf29e48ff"
D/QBASDK  ( 9477):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  ( 9477):     Referrer-Policy=strict-origin-when-cross-origin
D/QBASDK  ( 9477):     Server=QuickBlox
D/QBASDK  ( 9477):     Strict-Transport-Security=max-age=0; includeSubDomains
D/QBASDK  ( 9477):     X-Android-Received-Millis=1676609119378
D/QBASDK  ( 9477):     X-Android-Response-Source=NETWORK 200
D/QBASDK  ( 9477):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  ( 9477):     X-Android-Sent-Millis=1676609119016
D/QBASDK  ( 9477):     X-Content-Type-Options=nosniff
D/QBASDK  ( 9477):     X-Download-Options=noopen
D/QBASDK  ( 9477):     X-Frame-Options=SAMEORIGIN
D/QBASDK  ( 9477):     X-Permitted-Cross-Domain-Policies=none
D/QBASDK  ( 9477):     X-Request-Id=3af07287-3413-451f-ac31-1034694a015e
D/QBASDK  ( 9477):     X-Runtime=0.009134
D/QBASDK  ( 9477):     X-XSS-Protection=1; mode=block
D/QBASDK  ( 9477): BODY
D/QBASDK  ( 9477):     '{"api_endpoint":"https://api.quickblox.com","chat_endpoint":"chat.quickblox.com","turnserver_endpoint":"turn.quickblox.com"}'
D/QBASDK  ( 9477): 
D/QBASDK  ( 9477): Retrieved custom endpoints. ApiEndpoint: https://api.quickblox.com, ChatEndpoint: chat.quickblox.com
D/Request build: ( 9477): application_id=**HIDDEN**&auth_key=**HIDDEN**&nonce=-1332204257&timestamp=1676609119
D/QBASDK  ( 9477): =========================================================
D/QBASDK  ( 9477): === REQUEST ==== cf3a84ab-6ad0-47f1-af71-3c92ae398b59 ===
D/QBASDK  ( 9477): REQUEST
D/QBASDK  ( 9477):     POST https://api.quickblox.com/session.json
D/QBASDK  ( 9477): HEADERS
D/QBASDK  ( 9477):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  ( 9477):     QB-SDK=Android 4.0.0
D/QBASDK  ( 9477): PARAMETERS
D/QBASDK  ( 9477):     application_id=**HIDDEN**
D/QBASDK  ( 9477):     auth_key=**HIDDEN**
D/QBASDK  ( 9477):     nonce=-1332204257
D/QBASDK  ( 9477):     timestamp=1676609119
D/QBASDK  ( 9477):     signature=20198f26779380ac3fe187d2ce7a253d94286ae1
D/QBASDK  ( 9477): INLINE
D/QBASDK  ( 9477):     POST https://api.quickblox.com/session.json?application_id=**HIDDEN**&auth_key=**HIDDEN**&nonce=-1332204257&timestamp=1676609119&signature=20198f26779380ac3fe187d2ce7a253d94286ae1
D/TrafficStats( 9477): tagSocket(160) with statsTag=0xffffffff, statsUid=-1
D/EGL_emulation( 9477): app_time_stats: avg=89.32ms min=1.00ms max=1310.56ms count=15
D/EGL_emulation( 9477): app_time_stats: avg=201.77ms min=6.59ms max=506.76ms count=5
D/QBASDK  ( 9477): *********************************************************
D/QBASDK  ( 9477): *** RESPONSE *** cf3a84ab-6ad0-47f1-af71-3c92ae398b59 ***
D/QBASDK  ( 9477): STATUS : 201 
D/QBASDK  ( 9477): HEADERS
D/QBASDK  ( 9477):     cache-control=max-age=0, private, must-revalidate
D/QBASDK  ( 9477):     Connection=close
D/QBASDK  ( 9477):     Content-Length=410
D/QBASDK  ( 9477):     Content-Type=application/json; charset=utf-8
D/QBASDK  ( 9477):     Date=Fri, 17 Feb 2023 04:45:20 GMT
D/QBASDK  ( 9477):     QB-Token-ExpirationDate=2023-02-17 06:45:20 UTC
D/QBASDK  ( 9477):     Server=QuickBlox
D/QBASDK  ( 9477):     X-Android-Received-Millis=1676609120245
D/QBASDK  ( 9477):     X-Android-Response-Source=NETWORK 201
D/QBASDK  ( 9477):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  ( 9477):     X-Android-Sent-Millis=1676609119959
D/QBASDK  ( 9477):     x-request-id=F0SDHK2_ylXUqWULKmwh
D/QBASDK  ( 9477): BODY
D/QBASDK  ( 9477):     '{"session":{"_id":"0","application_id":99408,"created_at":"2023-02-17T04:45:20Z","id":0,"nonce":"-1332204257","token":**HIDDEN**,"ts":1676609119,"updated_at":"2023-02-17T04:45:20Z","user_id":0}}'
D/QBASDK  ( 9477): 
D/QBASDK  ( 9477): QBSessionListener onSessionCreated: WITHOUT USER
D/QBASDK  ( 9477): =========================================================
D/QBASDK  ( 9477): === REQUEST ==== 8d4d5074-de4a-484a-90b8-7238269b8a70 ===
D/QBASDK  ( 9477): REQUEST
D/QBASDK  ( 9477):     POST https://api.quickblox.com/login.json
D/QBASDK  ( 9477): HEADERS
D/QBASDK  ( 9477):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  ( 9477):     QB-SDK=Android 4.0.0
D/QBASDK  ( 9477):     QB-Token=**HIDDEN**
D/QBASDK  ( 9477): PARAMETERS
D/QBASDK  ( 9477):     login=yoseptara@gmail.com
D/QBASDK  ( 9477):     password=yoseptara@gmail.com
D/QBASDK  ( 9477): INLINE
D/QBASDK  ( 9477):     POST https://api.quickblox.com/login.json?login=yoseptara%40gmail.com&password=**HIDDEN**
D/TrafficStats( 9477): tagSocket(142) with statsTag=0xffffffff, statsUid=-1
I/winlifeapp.user( 9477): NativeAlloc concurrent copying GC freed 103014(4171KB) AllocSpace objects, 24(608KB) LOS objects, 49% free, 6447KB/12MB, paused 64us,86us total 104.470ms
D/QBASDK  ( 9477): *********************************************************
D/QBASDK  ( 9477): *** RESPONSE *** 8d4d5074-de4a-484a-90b8-7238269b8a70 ***
D/QBASDK  ( 9477): STATUS : 202 
D/QBASDK  ( 9477): HEADERS
D/QBASDK  ( 9477):     cache-control=max-age=0, private, must-revalidate
D/QBASDK  ( 9477):     Connection=close
D/QBASDK  ( 9477):     Content-Length=394
D/QBASDK  ( 9477):     Content-Type=application/json; charset=utf-8
D/QBASDK  ( 9477):     Date=Fri, 17 Feb 2023 04:45:21 GMT
D/QBASDK  ( 9477):     QB-Token-ExpirationDate=2023-02-17 06:45:20 UTC
D/QBASDK  ( 9477):     Server=QuickBlox
D/QBASDK  ( 9477):     X-Android-Received-Millis=1676609121324
D/QBASDK  ( 9477):     X-Android-Response-Source=NETWORK 202
D/QBASDK  ( 9477):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  ( 9477):     X-Android-Sent-Millis=1676609121010
D/QBASDK  ( 9477):     x-request-id=F0SDHOxmkC5AUt8KMEwh
D/QBASDK  ( 9477): BODY
D/QBASDK  ( 9477):     '{"user":{"age_over16":false,"blob_id":null,"created_at":"2023-01-21T03:35:42Z","custom_data":null,"email":"yoseptara@gmail.com","external_user_id":null,"facebook_id":null,"full_name":null,"id":136635855,"last_request_at":"2023-02-17T04:45:21Z","login":"yoseptara@gmail.com","parents_contacts":"","phone":null,"twitter_id":null,"updated_at":"2023-02-17T04:45:21Z","user_tags":"","website":null}}'
D/QBASDK  ( 9477): 
```

3. Requst/Response (when error occurs) :
```
D/QBASDK  ( 4787): =========================================================
D/QBASDK  ( 4787): === REQUEST ==== 9437dc07-4546-40d0-bd42-775826bf0b89 ===
D/QBASDK  ( 4787): REQUEST
D/QBASDK  ( 4787):     POST https://api.quickblox.com/login.json
D/QBASDK  ( 4787): HEADERS
D/QBASDK  ( 4787):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  ( 4787):     QB-SDK=Android 4.0.0
D/QBASDK  ( 4787):     QB-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6ImFwcGxpY2F0aW9uIiwiYXBwbGljYXRpb25faWQiOjk5NDA4LCJpYXQiOjE2NzY2MTc1MjU0NzM4OTJ9.S8JUQcy86fmihNEV4bVbxkWbXn5OyWLz1Y3eomjhUTGV_mOUHL1iN33YnXbfmbWhyopYAhzmJ9sewugXY0TTAw
D/QBASDK  ( 4787): PARAMETERS
D/QBASDK  ( 4787):     login=yoseptara@gmail.com
D/QBASDK  ( 4787):     password=yoseptara@gmail.com
D/QBASDK  ( 4787): INLINE
D/QBASDK  ( 4787):     POST https://api.quickblox.com/login.json?login=yoseptara%40gmail.com&password=yoseptara%40gmail.com
D/InsetsController( 4787): show(ime(), fromIme=true)
D/EGL_emulation( 4787): app_time_stats: avg=447.98ms min=0.85ms max=8847.46ms count=20
D/TrafficStats( 4787): tagSocket(123) with statsTag=0xffffffff, statsUid=-1
D/EGL_emulation( 4787): app_time_stats: avg=36.93ms min=4.45ms max=434.05ms count=27
D/QBASDK  ( 4787): *********************************************************
D/QBASDK  ( 4787): *** RESPONSE *** 9437dc07-4546-40d0-bd42-775826bf0b89 ***
D/QBASDK  ( 4787): STATUS : 401 
D/QBASDK  ( 4787): HEADERS
D/QBASDK  ( 4787):     cache-control=max-age=0, private, must-revalidate
D/QBASDK  ( 4787):     Connection=close
D/QBASDK  ( 4787):     Content-Length=55
D/QBASDK  ( 4787):     Content-Type=application/json; charset=utf-8
D/QBASDK  ( 4787):     Date=Sun, 19 Feb 2023 03:23:14 GMT
D/QBASDK  ( 4787):     Server=QuickBlox
D/QBASDK  ( 4787):     X-Android-Received-Millis=1676776995974
D/QBASDK  ( 4787):     X-Android-Response-Source=NETWORK 401
D/QBASDK  ( 4787):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  ( 4787):     X-Android-Sent-Millis=1676776995710
D/QBASDK  ( 4787):     x-request-id=F0UbyuhH_xSLf_Ib91oD
D/QBASDK  ( 4787): BODY
D/QBASDK  ( 4787):     '{"errors":{"base":["Required session does not exist"]}}'
D/QBASDK  ( 4787): 
I/flutter ( 4787): (qbService.loginQB) error : PlatformException(base Required session does not exist, null, null, null)
I/flutter ( 4787): #0      QuickbloxService.loginOrRegister (package:winlife/data/provider/quickblox_service.dart:249:7)
I/flutter ( 4787): <asynchronous suspension>
I/flutter ( 4787): #1      QuickbloxService.initSession (package:winlife/data/provider/quickblox_service.dart:79:5)
I/flutter ( 4787): <asynchronous suspension>
I/flutter ( 4787): #2      CreateOrderController.reinitQbSession (package:winlife/controller/create_order_controller.dart:224:5)
I/flutter ( 4787): <asynchronous suspension>
I/flutter ( 4787): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 4787): (qbService.loginQB) error : PlatformException(base Required session does not exist, null, null, null)
I/flutter ( 4787): #0      QuickbloxService.loginOrRegister (package:winlife/data/provider/quickblox_service.dart:249:7)
I/flutter ( 4787): <asynchronous suspension>
I/flutter ( 4787): #1      QuickbloxService.initSession (package:winlife/data/provider/quickblox_service.dart:79:5)
I/flutter ( 4787): <asynchronous suspension>
I/flutter ( 4787): #2      CreateOrderController.reinitQbSession (package:winlife/controller/create_order_controller.dart:224:5)
I/flutter ( 4787): <asynchronous suspension>
I/flutter ( 4787): ----------------------------------------------------
```

I think it is caused by session expiration time and then when I try to use QB.auth.login again, session is not re-created (there is no request to https://api.quickblox.com/session.json). Any solution for this? Thanks

**Comment by kirillTolmachev** [comment]
Hello @yoseptara 
Now we have released a new version of Flutter  [QuickBlox SDK 0.12.3](https://pub.dev/packages/quickblox_sdk/changelog#0123) where we fixed some issues with session logic on Android side.
Please update the SDK version and provide us feedback.

**Comment by yoseptara** [comment]
> Hello @yoseptara Now we have released a new version of Flutter [QuickBlox SDK 0.12.3](https://pub.dev/packages/quickblox_sdk/changelog#0123) where we fixed some issues with session logic on Android side. Please update the SDK version and provide us feedback.

Hello, I have updated the quickblox sdk to 0.12.3 and use the same code I mentioned above, but still get the errors.
I use Android 13 emulator (api level 33) for testing

**Comment by AbdurrehmanSubhani** [comment]
I also do get the same error after launching my application after say 2-3 hours.
After doing some research i came across this concept of user session tokens being valid for only 2 hours, does this issue relate to that?
If so, what's the best way to create a new valid user session token ideally without the user having to enter their login credentials again?

I've also tried to intialise the sdk again but i get this same error again while trying to login with the user's credentials and as mentioned by @yoseptara clearing data/reinstalling the app solves this login issue

Im using quickblox_sdk: ^0.12.2 as of now

**Comment by kirillTolmachev** [comment]
@AbdurrehmanSubhani , @yoseptara 
The issue relates to the wrong token. I mean a token with an expired date.
To resolve the issue we need Rest logs from your application like those provided by @yoseptara, but in the logs, we need to see the token. In the current logs, the token is hidden.

Please provide logs and we will check. At the time from our side, we also are checking the issue.

Urgent information. If you haven't updated yet to SDK version 0.12.3, please do it.

**Comment by yoseptara** [comment]
> @AbdurrehmanSubhani , @yoseptara The issue relates to the wrong token. I mean a token with an expired date. To resolve the issue we need Rest logs from your application like those provided by @yoseptara, but in the logs, we need to see the token. In the current logs, the token is hidden.
> 
> Please provide logs and we will check. At the time from our side, we also are checking the issue.
> 
> Urgent information. If you haven't updated yet to SDK version 0.12.3, please do it.

Hello, this is my updated logs.

Before error occurs :
```
D/QBASDK  (25276): =========================================================
D/QBASDK  (25276): === REQUEST ==== 70d9be09-3875-4702-8292-4784de8b863f ===
D/QBASDK  (25276): REQUEST
D/QBASDK  (25276):     GET https://api.quickblox.com/account_settings.json
D/QBASDK  (25276): HEADERS
D/QBASDK  (25276):     QB-Account-Key=**HIDDEN**
D/QBASDK  (25276): PARAMETERS
D/QBASDK  (25276): 
D/QBASDK  (25276): INLINE
D/QBASDK  (25276):     GET https://api.quickblox.com/account_settings.json
D/InputMethodManager(25276): showSoftInput() view=io.flutter.embedding.android.FlutterView{ec01a4 VFE...... .F...... 0,0-1080,1878 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager(25276): showSoftInput() view=io.flutter.embedding.android.FlutterView{ec01a4 VFE...... .F...... 0,0-1080,1878 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController(25276): show(ime(), fromIme=true)
D/EGL_emulation(25276): app_time_stats: avg=596.59ms min=2.10ms max=11155.50ms count=19
D/EGL_emulation(25276): app_time_stats: avg=35.58ms min=2.89ms max=253.74ms count=26
D/QBASDK  (25276): *********************************************************
D/QBASDK  (25276): *** RESPONSE *** 70d9be09-3875-4702-8292-4784de8b863f ***
D/QBASDK  (25276): STATUS : 200 
D/QBASDK  (25276): HEADERS
D/QBASDK  (25276):     Access-Control-Allow-Origin=*
D/QBASDK  (25276):     Cache-Control=max-age=0, private, must-revalidate
D/QBASDK  (25276):     Connection=close
D/QBASDK  (25276):     Content-Length=124
D/QBASDK  (25276):     Content-Security-Policy=default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data: www.google-analytics.com; object-src 'none'; script-src 'self' https: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com; style-src 'self' https: 'unsafe-inline'
D/QBASDK  (25276):     Content-Type=application/json; charset=utf-8
D/QBASDK  (25276):     Date=Sun, 05 Mar 2023 10:36:36 GMT
D/QBASDK  (25276):     ETag=W/"e545561202e48f08ebd0483cf29e48ff"
D/QBASDK  (25276):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  (25276):     Referrer-Policy=strict-origin-when-cross-origin
D/QBASDK  (25276):     Server=QuickBlox
D/QBASDK  (25276):     Strict-Transport-Security=max-age=0; includeSubDomains
D/QBASDK  (25276):     X-Android-Received-Millis=1678012596752
D/QBASDK  (25276):     X-Android-Response-Source=NETWORK 200
D/QBASDK  (25276):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  (25276):     X-Android-Sent-Millis=1678012596486
D/QBASDK  (25276):     X-Content-Type-Options=nosniff
D/QBASDK  (25276):     X-Download-Options=noopen
D/QBASDK  (25276):     X-Frame-Options=SAMEORIGIN
D/QBASDK  (25276):     X-Permitted-Cross-Domain-Policies=none
D/QBASDK  (25276):     X-Request-Id=ecf2a3ec-e945-4eec-9e33-c9d3aff94370
D/QBASDK  (25276):     X-Runtime=0.009036
D/QBASDK  (25276):     X-XSS-Protection=1; mode=block
D/QBASDK  (25276): BODY
D/QBASDK  (25276):     '{"api_endpoint":"https://api.quickblox.com","chat_endpoint":"chat.quickblox.com","turnserver_endpoint":"turn.quickblox.com"}'
D/QBASDK  (25276): 
D/QBASDK  (25276): Retrieved custom endpoints. ApiEndpoint: https://api.quickblox.com, ChatEndpoint: chat.quickblox.com
D/Request build: (25276): application_id=**HIDDEN**&auth_key=**HIDDEN**&nonce=-769119602&timestamp=1678012596
D/QBASDK  (25276): =========================================================
D/QBASDK  (25276): === REQUEST ==== 0272f427-cfae-4fcd-878f-ca52ad9d360e ===
D/QBASDK  (25276): REQUEST
D/QBASDK  (25276):     POST https://api.quickblox.com/session.json
D/QBASDK  (25276): HEADERS
D/QBASDK  (25276):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  (25276):     QB-SDK=Android 4.0.2
D/QBASDK  (25276): PARAMETERS
D/QBASDK  (25276):     application_id=**HIDDEN**
D/QBASDK  (25276):     auth_key=**HIDDEN**
D/QBASDK  (25276):     nonce=-769119602
D/QBASDK  (25276):     timestamp=1678012596
D/QBASDK  (25276):     signature=d83de03e294208c90a8dd5a1a4029d28ee38c9f2
D/QBASDK  (25276): INLINE
D/QBASDK  (25276):     POST https://api.quickblox.com/session.json?application_id=**HIDDEN**&auth_key=**HIDDEN**&nonce=-769119602&timestamp=1678012596&signature=d83de03e294208c90a8dd5a1a4029d28ee38c9f2
D/EGL_emulation(25276): app_time_stats: avg=500.09ms min=499.96ms max=500.21ms count=2
D/QBASDK  (25276): *********************************************************
D/QBASDK  (25276): *** RESPONSE *** 0272f427-cfae-4fcd-878f-ca52ad9d360e ***
D/QBASDK  (25276): STATUS : 201 
D/QBASDK  (25276): HEADERS
D/QBASDK  (25276):     cache-control=max-age=0, private, must-revalidate
D/QBASDK  (25276):     Connection=close
D/QBASDK  (25276):     Content-Length=409
D/QBASDK  (25276):     Content-Type=application/json; charset=utf-8
D/QBASDK  (25276):     Date=Sun, 05 Mar 2023 10:36:36 GMT
D/QBASDK  (25276):     QB-Token-ExpirationDate=2023-03-05 12:36:36 UTC
D/QBASDK  (25276):     Server=QuickBlox
D/QBASDK  (25276):     X-Android-Received-Millis=1678012597633
D/QBASDK  (25276):     X-Android-Response-Source=NETWORK 201
D/QBASDK  (25276):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  (25276):     X-Android-Sent-Millis=1678012597290
D/QBASDK  (25276):     x-request-id=F0l_kPpzSdK9UOCizjDj
D/QBASDK  (25276): BODY
D/QBASDK  (25276):     '{"session":{"_id":"0","application_id":99408,"created_at":"2023-03-05T10:36:36Z","id":0,"nonce":"-769119602","token":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6ImFwcGxpY2F0aW9uIiwiYXBwbGljYXRpb25faWQiOjk5NDA4LCJpYXQiOjE2NzgwMTI1OTY5MDM1NjV9.ZGWn6C1NUxTVFAhT0V_w28ZndTmgxkaJpXdwpZiWpssZcsJdL5sSdUMVyYKkYYknyl0u1PStqh4RqAxZGxZ7jQ","ts":1678012596,"updated_at":"2023-03-05T10:36:36Z","user_id":0}}'
D/QBASDK  (25276): 
D/QBASDK  (25276): QBSessionListener onSessionCreated: WITHOUT USER
D/QBASDK  (25276): =========================================================
D/QBASDK  (25276): === REQUEST ==== 9cbee687-5b51-4e73-9765-3df0f848ef5a ===
D/QBASDK  (25276): REQUEST
D/QBASDK  (25276):     POST https://api.quickblox.com/login.json
D/QBASDK  (25276): HEADERS
D/QBASDK  (25276):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  (25276):     QB-SDK=Android 4.0.2
D/QBASDK  (25276):     QB-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6ImFwcGxpY2F0aW9uIiwiYXBwbGljYXRpb25faWQiOjk5NDA4LCJpYXQiOjE2NzgwMTI1OTY5MDM1NjV9.ZGWn6C1NUxTVFAhT0V_w28ZndTmgxkaJpXdwpZiWpssZcsJdL5sSdUMVyYKkYYknyl0u1PStqh4RqAxZGxZ7jQ
D/QBASDK  (25276): PARAMETERS
D/QBASDK  (25276):     login=yoseptara@gmail.com
D/QBASDK  (25276):     password=yoseptara@gmail.com
D/QBASDK  (25276): INLINE
D/QBASDK  (25276):     POST https://api.quickblox.com/login.json?login=yoseptara%40gmail.com&password=yoseptara%40gmail.com
D/QBASDK  (25276): *********************************************************
D/QBASDK  (25276): *** RESPONSE *** 9cbee687-5b51-4e73-9765-3df0f848ef5a ***
D/QBASDK  (25276): STATUS : 202 
D/QBASDK  (25276): HEADERS
D/QBASDK  (25276):     cache-control=max-age=0, private, must-revalidate
D/QBASDK  (25276):     Connection=close
D/QBASDK  (25276):     Content-Length=394
D/QBASDK  (25276):     Content-Type=application/json; charset=utf-8
D/QBASDK  (25276):     Date=Sun, 05 Mar 2023 10:36:37 GMT
D/QBASDK  (25276):     QB-Token-ExpirationDate=2023-03-05 12:36:36 UTC
D/QBASDK  (25276):     Server=QuickBlox
D/QBASDK  (25276):     X-Android-Received-Millis=1678012598523
D/QBASDK  (25276):     X-Android-Response-Source=NETWORK 202
D/QBASDK  (25276):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  (25276):     X-Android-Sent-Millis=1678012598230
D/QBASDK  (25276):     x-request-id=F0l_kTLoMPRQd3cCjsoH
D/QBASDK  (25276): BODY
D/QBASDK  (25276):     '{"user":{"age_over16":false,"blob_id":null,"created_at":"2023-01-21T03:35:42Z","custom_data":null,"email":"yoseptara@gmail.com","external_user_id":null,"facebook_id":null,"full_name":null,"id":136635855,"last_request_at":"2023-03-05T10:36:37Z","login":"yoseptara@gmail.com","parents_contacts":"","phone":null,"twitter_id":null,"updated_at":"2023-03-05T10:36:37Z","user_tags":"","website":null}}'
```

After error occurs :
```
D/QBASDK  ( 5537): =========================================================
D/QBASDK  ( 5537): === REQUEST ==== ca5457a4-432a-4c18-980a-ef0e79616ee0 ===
D/QBASDK  ( 5537): REQUEST
D/QBASDK  ( 5537):     POST https://api.quickblox.com/login.json
D/QBASDK  ( 5537): HEADERS
D/QBASDK  ( 5537):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  ( 5537):     QB-SDK=Android 4.0.2
D/QBASDK  ( 5537):     QB-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdHlwZSI6ImFwcGxpY2F0aW9uIiwiYXBwbGljYXRpb25faWQiOjk5NDA4LCJpYXQiOjE2NzgwMTI1OTY5MDM1NjV9.ZGWn6C1NUxTVFAhT0V_w28ZndTmgxkaJpXdwpZiWpssZcsJdL5sSdUMVyYKkYYknyl0u1PStqh4RqAxZGxZ7jQ
D/QBASDK  ( 5537): PARAMETERS
D/QBASDK  ( 5537):     login=yoseptara@gmail.com
D/QBASDK  ( 5537):     password=yoseptara@gmail.com
D/QBASDK  ( 5537): INLINE
D/QBASDK  ( 5537):     POST https://api.quickblox.com/login.json?login=yoseptara%40gmail.com&password=yoseptara%40gmail.com
D/EGL_emulation( 5537): app_time_stats: avg=2473.56ms min=102.09ms max=11818.25ms count=5
D/InputMethodManager( 5537): showSoftInput() view=io.flutter.embedding.android.FlutterView{93491ee VFE...... .F...... 0,0-1080,1878 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 5537): showSoftInput() view=io.flutter.embedding.android.FlutterView{93491ee VFE...... .F...... 0,0-1080,1878 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 5537): show(ime(), fromIme=true)
D/EGL_emulation( 5537): app_time_stats: avg=647.90ms min=2.41ms max=12184.18ms count=19
D/QBASDK  ( 5537): *********************************************************
D/QBASDK  ( 5537): *** RESPONSE *** ca5457a4-432a-4c18-980a-ef0e79616ee0 ***
D/QBASDK  ( 5537): STATUS : 401 
D/QBASDK  ( 5537): HEADERS
D/QBASDK  ( 5537):     cache-control=max-age=0, private, must-revalidate
D/QBASDK  ( 5537):     Connection=close
D/QBASDK  ( 5537):     Content-Length=55
D/QBASDK  ( 5537):     Content-Type=application/json; charset=utf-8
D/QBASDK  ( 5537):     Date=Mon, 06 Mar 2023 02:47:17 GMT
D/QBASDK  ( 5537):     Server=QuickBlox
D/QBASDK  ( 5537):     X-Android-Received-Millis=1678070837608
D/QBASDK  ( 5537):     X-Android-Response-Source=NETWORK 401
D/QBASDK  ( 5537):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  ( 5537):     X-Android-Sent-Millis=1678070837328
D/QBASDK  ( 5537):     x-request-id=F0m0iRrWFaVs_nmnrWqj
D/QBASDK  ( 5537): BODY
D/QBASDK  ( 5537):     '{"errors":{"base":["Required session does not exist"]}}'
D/QBASDK  ( 5537): 
I/flutter ( 5537): (QuickbloxService, loginOrRegister) error is PlatformException
I/flutter ( 5537): (QuickbloxService, loginOrRegister) cek exception code : base Required session does not exist
I/flutter ( 5537): (QuickbloxService, loginOrRegister) cek exception message : null
I/flutter ( 5537): (QuickbloxService, loginOrRegister) cek exception details : null
I/flutter ( 5537): (qbService.loginQB) error : PlatformException(base Required session does not exist, null, null, null)
I/flutter ( 5537): #0      QuickbloxService.loginOrRegister (package:winlife/data/provider/quickblox_service.dart:254:7)
I/flutter ( 5537): <asynchronous suspension>
I/flutter ( 5537): #1      QuickbloxService.initSession (package:winlife/data/provider/quickblox_service.dart:79:5)
I/flutter ( 5537): <asynchronous suspension>
I/flutter ( 5537): #2      CreateOrderController.reinitQbSession (package:winlife/controller/create_order_controller.dart:224:5)
I/flutter ( 5537): <asynchronous suspension>
I/flutter ( 5537): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5537): (qbService.loginQB) error : PlatformException(base Required session does not exist, null, null, null)
I/flutter ( 5537): #0      QuickbloxService.loginOrRegister (package:winlife/data/provider/quickblox_service.dart:254:7)
I/flutter ( 5537): <asynchronous suspension>
I/flutter ( 5537): #1      QuickbloxService.initSession (package:winlife/data/provider/quickblox_service.dart:79:5)
I/flutter ( 5537): <asynchronous suspension>
I/flutter ( 5537): #2      CreateOrderController.reinitQbSession (package:winlife/controller/create_order_controller.dart:224:5)
I/flutter ( 5537): <asynchronous suspension>
I/flutter ( 5537): ----------------------------------------------------
```

**Comment by kirillTolmachev** [comment]
@yoseptara 
Thank you for the logs.

Now I have additional questions.

1. How do you init QB SDK?
I mean we have two flows:
* QB.settings.init(APPLICATION_ID, AUTHORIZATION_KEY, AUTHORIZATION_SECRET, ACCOUNT_KEY);
* QB.settings.initWithAppId(APPLICATION_ID);

2. Do you set a token by your hands, set session, or just call login?
* QB.auth.startSessionWithToken(TOKEN);
* QB.auth.login(USER_LOGIN, USER_PASSWORD);
* QB.auth.setSession(session);

**Comment by yoseptara** [comment]
> @yoseptara Thank you for the logs.
> 
> Now I have additional questions.
> 
> 1. How do you init QB SDK?
>    I mean we have two flows:
> 
> * QB.settings.init(APPLICATION_ID, AUTHORIZATION_KEY, AUTHORIZATION_SECRET, ACCOUNT_KEY);
> * QB.settings.initWithAppId(APPLICATION_ID);
> 
> 2. Do you set a token by your hands, set session, or just call login?
> 
> * QB.auth.startSessionWithToken(TOKEN);
> * QB.auth.login(USER_LOGIN, USER_PASSWORD);
> * QB.auth.setSession(session);

Hello,

1. I use QB.settings.init(APPLICATION_ID, AUTHORIZATION_KEY, AUTHORIZATION_SECRET, ACCOUNT_KEY);
2. I only use QB.auth.login(USER_LOGIN, USER_PASSWORD);

I don't use QB.auth.startSessionWithToken(TOKEN); because I don't know where can I get the token and I didn't see the information about this function on documentation.

And I don't use QB.auth.setSession(session); because I save the session as variable in my QuickbloxService class and never use getSession() function

**Comment by AbdurrehmanSubhani** [comment]
> @yoseptara Thank you for the logs.
> 
> Now I have additional questions.
> 
> 1. How do you init QB SDK?
>    I mean we have two flows:
> 
> * QB.settings.init(APPLICATION_ID, AUTHORIZATION_KEY, AUTHORIZATION_SECRET, ACCOUNT_KEY);
> * QB.settings.initWithAppId(APPLICATION_ID);
> 
> 2. Do you set a token by your hands, set session, or just call login?
> 
> * QB.auth.startSessionWithToken(TOKEN);
> * QB.auth.login(USER_LOGIN, USER_PASSWORD);
> * QB.auth.setSession(session);



> @yoseptara Thank you for the logs.
> 
> Now I have additional questions.
> 
> 1. How do you init QB SDK?
>    I mean we have two flows:
> 
> * QB.settings.init(APPLICATION_ID, AUTHORIZATION_KEY, AUTHORIZATION_SECRET, ACCOUNT_KEY);
> * QB.settings.initWithAppId(APPLICATION_ID);
> 
> 2. Do you set a token by your hands, set session, or just call login?
> 
> * QB.auth.startSessionWithToken(TOKEN);
> * QB.auth.login(USER_LOGIN, USER_PASSWORD);
> * QB.auth.setSession(session);

Hey @kirillTolmachev !,
Here's my auth flow:
1. Get session token using: await QB.auth.getSession();
2. Check if this session is null
3. If this session is null, then do the following:

--> Initialise Quickblox sdk:
--> 3.1.1  await QB.settings.init(APP_ID,AUTH_KEY,AUTH_SECRET,ACCOUNT_KEY);

--> Login to create user session using username and password (base session does not exist error comes at this point):
--> 3.1.2 await QB.auth.login("username","password");

--> connect to chat:
--> 3.1.3 await QB.chat.connect(qbUser!.id!, credentialsModel!.password);

--> initialise webRTC:
--> 3.1.4 await QB.webrtc.init();

I assume the quickblox sdk somehow does not set the base session correctly IF the sdk has been initialised previously using the await QB.settings.init(APP_ID,AUTH_KEY,AUTH_SECRET,ACCOUNT_KEY); method.
Im assuming this because deleting and reinstalling the application works fine with the exact same code

**Comment by kirillTolmachev** [comment]
@yoseptara @AbdurrehmanSubhani 
I have tested your flow and didn't reproduce the problem.

Test code:
```
Future<void> _testSessionIssueQB() async {
    await QB.settings.enableLogging();
    await QB.settings.enableXMPPLogging();

    await QB.settings.init(APP_ID, AUTH_KEY, AUTH_SECRET, ACCOUNT_KEY, apiEndpoint: API_ENDPOINT, chatEndpoint: CHAT_ENDPOINT);

    QBSession? session = await QB.auth.getSession();
    if (session == null) {
      try {
        await QB.auth.login(USER_LOGIN, USER_PASSWORD);
      } on PlatformException catch (e) {
        print("Exception from auth.login()");
      }
    }

    try {
      List<QBDialog?> userList = await QB.chat.getDialogs();
      int count = userList.length;
      print("Loaded dialogs $count");
    } on PlatformException catch (e) {
      print("Exception from chat.getDialogs()");
    }
  }
```
The method calls when an application starts in **main.dart** file. I tried open application after 2, 3, and 4 hours and always token updated correctly. I tried to close application or just go to background for 2,3,4 hours and token updated correctly. 

Important notice, the session didn't have **null** value in all my attempts, because session is stored in SDK and to clean it we need to reinstall application or delete session manually by calling **QB.auth.logout()** or **QB.users.deleteUser()**

I think we missed some steps. First of all, I need to reproduce the issue to fix it. 
Please double-check your code, maybe you invoke **QB.auth.setSession(session)** somewhere.

If you won't find any additional steps, then please check my code in your application. If the issue will be still reproducing please contact our support team. We will need access to your source code to investigate and fix the issue.

**Comment by yoseptara** [comment]
> @yoseptara @AbdurrehmanSubhani I have tested your flow and didn't reproduce the problem.
> 
> Test code:
> 
> ```
> Future<void> _testSessionIssueQB() async {
>     await QB.settings.enableLogging();
>     await QB.settings.enableXMPPLogging();
> 
>     await QB.settings.init(APP_ID, AUTH_KEY, AUTH_SECRET, ACCOUNT_KEY, apiEndpoint: API_ENDPOINT, chatEndpoint: CHAT_ENDPOINT);
> 
>     QBSession? session = await QB.auth.getSession();
>     if (session == null) {
>       try {
>         await QB.auth.login(USER_LOGIN, USER_PASSWORD);
>       } on PlatformException catch (e) {
>         print("Exception from auth.login()");
>       }
>     }
> 
>     try {
>       List<QBDialog?> userList = await QB.chat.getDialogs();
>       int count = userList.length;
>       print("Loaded dialogs $count");
>     } on PlatformException catch (e) {
>       print("Exception from chat.getDialogs()");
>     }
>   }
> ```
> 
> The method calls when an application starts in **main.dart** file. I tried open application after 2, 3, and 4 hours and always token updated correctly. I tried to close application or just go to background for 2,3,4 hours and token updated correctly.
> 
> Important notice, the session didn't have **null** value in all my attempts, because session is stored in SDK and to clean it we need to reinstall application or delete session manually by calling **QB.auth.logout()** or **QB.users.deleteUser()**
> 
> I think we missed some steps. First of all, I need to reproduce the issue to fix it. Please double-check your code, maybe you invoke **QB.auth.setSession(session)** somewhere.
> 
> If you won't find any additional steps, then please check my code in your application. If the issue will be still reproducing please contact our support team. We will need access to your source code to investigate and fix the issue.

Hello thanks for all of the replies. After I checked it again, I think the issue is caused by using the returned session of QB.auth.login as param of QB.auth.setSession.

Example that reproduce the error :
```
 QBLoginResult result = await QB.auth.login(USER_LOGIN, USER_PASSWORD);
  await QB.auth.setSession(result.qbSession!);
```

And after I commented "await QB.auth.setSession(result.qbSession!);" , the error doesnt occur anymore.

**Comment by kirillTolmachev** [comment]
@yoseptara 
Yes, exactly. 
invoking method **setSession** - means you set the session by your hand and SDK won't manage session (token) updating mechanism it's why session (token) wasn't updating. 
By default you don't need to manage session (token), it managing by SDK automatically.
Thank you for your research and answer.

**Comment by AbdurrehmanSubhani** [comment]
Thanks for helping out @kirillTolmachev 💯
